version: '3.9'

name: ${NAME:- video-title-remover }

services:
  app:
    image: video-subtitle-remover:1.1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:- 8090 }:8090" # 将容器的8000端口映射到宿主机的8000端口
    environment:
      - pools=${POOLS:- 4}
      - MODE=${MODE:- sttn}
      - STTN_NEIGHBOR_STRIDE=${STTN_NEIGHBOR_STRIDE:- 5}
      - STTN_REFERENCE_LENGTH=${STTN_REFERENCE_LENGTH:- 10}
    volumes:
      - ${DATA_DIR:- ./data}:/app/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${DEVICE:-0}']
              capabilities: [ gpu ]