version: '3.9'

name: ${NAME:-video-title-remover}

services:
  app:
    image: video-subtitle-remover:1.2.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8090}:8090"
    environment:
      - pools=${POOLS:-4}
      - MODE=${MODE:-sttn}
      - STTN_NEIGHBOR_STRIDE=${STTN_NEIGHBOR_STRIDE:-5}
      - STTN_REFERENCE_LENGTH=${STTN_REFERENCE_LENGTH:-10}
    volumes:
      - ${DATA_DIR:-./data}:/app/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8090/connect || exit 1" ]
      interval: 30s
      timeout: 5s
      start_period: 300s
      retries: 3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${DEVICE:-0}']
              capabilities: [ gpu ]